const songs = [{
    "nid": "739",
    "title": "Sing Me ",
    "album":["testAlbum"],
"body": "John: vocal<br>Michael: piano and organ<br>Pete: electric guitar<br>Jos: drums<br>JT: bass<br><br>The history of working people in this world is filled with people of great courage, intelligence and heart...if we could only hear about them. Most are never mentioned in school history books. That's why we have to tell them...sing them...to one another over and over again.<br><br>Joe Hill (1879-1915) was a Swedish immigrant to America named Joseph Hillstrom. He was a songwriter and organizer for the Industrial Workers of the World (IWW). The IWW believed that every worker should belong to the same One Big Union. His music is loved and sung around the world.<br><br>Mary Harris Jones (1830-1930) was affectionately known as \"Mother Jones\" throughout the world. An Irish immigrant to America, she worked tirelessly for working people, especially miners and children. Her grave, in Springfield, IL, is still tended today by grateful workers.<br><br>Cesar Chavez (1927-1993 ) was the founder and president of the United Farm Workers (UFW), the union that represented migrant laborers in the agriculture field. A Chicano, Cesar was a moral force in the labor movement, championing immigrants of all races and inspiring people throughout the world with his doctrine of nonviolence.<br><br>John L. Lewis (1880-1969 ) was the fiery leader of the United Mine Workers. With his fearless personality and bushy eyebrows he was a bigger-than-life force in America during his lifetime. Go into any coal camp in, say, eastern Kentucky and in every home you'll find three pictures over the sofa: Jesus, Franklin Roosevelt, and John L. Lewis.<br><br>Tell 'bout the ones who walked on the line<br>The ones who stood out from the crowd<br>Who lifted their heads, who lifted their eyes<br>Who lifted their voice clear and loud<br><br>Chorus<br><br>Sing me one more 'cause I'm not tired yet<br>Don't leave one note out that's true<br>Tell me again, I don't want to forget<br>Sing me what they sang to you<br>Sing so I'll know what to do<br><br>Tell 'bout the ones who stood and said \"No\"When everyone else answered \"Yes\"The ones who played fair and demanded their share<br>When everyone settled for less<br><br>Chorus<br><br>Joe Hill, Mother Jones, Cesar Chavez, John L.<br>And the millions we don't know by name<br>Those in the past and those still standing fast<br>And those coming who'll carry the flame<br><br>Chorus<br><br>\u00a91997 John McCutcheon\/Appalsongs (ASCAP) & Si Kahn\/Joe Hill Music (ASCAP)<br>"
}, {
    "nid": "740",
    "title": "Friends Don't Let Friends",
    "album":["testAlbum"],
"body": "John: vocal and acoustic & electric guitars<br>Michael: organ<br>Pete: electric guitar<br>Jos: drums<br>Kevin: congas<br>JT: bass and harmony vocal<br>Jon: harmony vocal<br>Bobby: saxophone<br><br>Friends don't let friends miss out on a party<br>Friends don't let friends out of games that you play<br>Friends don't let friends down<br>Friends don't let friends down<br>Friends don't let friends alone in the dark<br>Friends don't let friends go astray<br><br>Chorus<br><br>Stand up for one another<br>That's where your true friends are found<br>Talking 'bout more than your sister or your brother<br>Stand up you're on solid ground<br>When friends don't let friends down<br><br>...eat lunch by themselves<br>...take more than their share<br>Friends don't let friends down (2x)<br>...pick on those smaller<br>...not play fair<br><br>Bridge<br><br>Sometimes you got to stand up all own your own<br>Just to find you're not so alone<br>Stand up on your own two feet<br>March to the tune of a different beat<br><br>...out of secret<br>...take on a bully alone<br>Friends don't let friends down (2x)<br>...talk mean about other friends<br>...not feel at home<br><br>\u00a91997 John McCutcheon\/Appalsongs (ASCAP) & Si Kahn\/Joe Hill Music (ASCAP)"
}, {
    "nid": "741",
    "title": "Running for President",
    "album":["testAlbum"],
"body": "John: vocal, guitar, and autoharp<br>Tim: mandolin<br>Michael: synthesizer<br>JT: bass and harmony vocal<br>Jon: harmony vocal<br>Cheryl: harmony vocal<br><br>I'm running for president<br>Won't you come with me?<br>If there's only one president<br>It's either he or she<br>But if we had two presidents<br>How much better that would be<br>I'm running for president<br>Won't you run with me?<br><br>We're running for president<br>Will you come along?<br>For even with two presidents<br>Both still could be wrong<br>But if we had three presidents<br>We could harmonize this song<br>We're running for president<br>Won't you come along?<br><br>We're running for president<br>Will you make it four?<br>Even with three presidents<br>We can always use more<br>No assistants or vices<br>With titles galore<br>We'll be know as presidents<br>One, two, three, and four<br><br>No one gets to gloat<br>And no one gets sore<br>It's simple arithmetic<br>Just add one more<br>More seats at the table<br>More room at the inn<br>One person, one vote<br>Let the party begin<br><br>We're running for president<br>A twelve-person slate<br>Life's so much more fun<br>When there's more on the plate<br>We've got loads of ideas<br>An plans to compare<br>We're running for president<br>Would you like to share?<br><br>\u00a91997 John McCutcheon\/Appalsongs (ASCAP) & Si Kahn\/Joe Hill Music (ASCAP)"
}, {
    "nid": "742",
    "title": "Safe at Home",
    "album":["testAlbum"],
"body": "John: vocal and guitar<br><br>My whole body's aching<br>There's blood on my knee<br>I tripped on a nail<br>That I didn't see<br>There's a bump on my pride<br>And a lump on my head<br>The whole family's gathered<br>To see I'm not dead<br><br>Chorus<br><br>I don't want excuses<br>I don't want your pity<br>What this family needs<br>Is a safety committee<br>It's something we need<br>I can't do it alone<br>In this dangerous world<br>A boy or a girl<br>At least should expect<br>To be safe at home<br><br>I hear at Mom's office<br>And down in Dad's plant<br>There's things that you can do<br>And others you can't<br>Rules to protect you<br>And help you feel safe<br>That's what I'm saying<br>We need in this place<br><br>Chorus<br><br>My whole body's trembling<br>'Cause there on my knee<br>Is some grown-up's hand<br>Where a hand shouldn't be<br>I jumped to my feet<br>And I ran to the door<br>Right past where that nail<br>Used to be in the floor<br><br>Chorus<br><br>Coda:<br><br>It's really not fair<br>I should wait till I'm grown<br>In this dangerous world<br>A boy or a girl<br>At least should expect<br>To be safe at home<br><br>\u00a91997 John McCutcheon\/Appalsongs (ASCAP) & Si Kahn\/Joe Hill Music (ASCAP)"
}, {
    "nid": "743",
    "title": "Bigger Than Yourself",
    "album":["testAlbum"],
"body": "John: vocal and guitars<br>Michael: piano and organ<br>Pete: electric guitar<br>Bob: electric guitar and bass<br>Jos: drums<br>JT: bass and harmony vocals<br>Jon: harmony vocals<br>Cheryl: harmony vocals<br><br>One night when I was sleeping<br>I dreamed I sailed upon the sea<br>A lot of kids I know from school<br>Were on that ship with me<br>When the wind began to howl<br>The waves began to pound<br>I got so scared, that ship was spinning<br>'Round and up and down<br>Then I looked back and saw the faces<br>Of the friends I knew so well<br>It's so much better to be here with them<br>Than out there by myself<br><br>Chorus<br><br>Everybody needs<br>Something bigger than themselves<br>We need to belong<br>To something bigger, bigger than ourselves<br><br>For we are all just sailors<br>On the sea and on the land<br>Every one of us sometimes<br>Will need a helping hand<br>Sometimes it takes a lot of friends<br>To help us get along<br>To back us up when we are right<br>And even when we're wrong<br>For one can only do so much<br>But lots of us can be<br>A steady ship that carries us<br>Across an angry sea<br><br>Chorus<br><br>\u00a91997 John McCutcheon\/Appalsongs (ASCAP) & Si Kahn\/Joe Hill Music (ASCAP)"
}];